---
abstract: 'Form Processing So Easy It Will Knock You Out'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Chloro
requires:
  List::AllUtils: 0
  Moose: 1.25
  MooseX::Params::Validate: 0
  MooseX::StrictConstructor: 0.15
  MooseX::Types: 0
  MooseX::Types::Common::String: 0
  Tie::IxHash: 0
  namespace::autoclean: 0.12
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Chloro
  repository: git://git.urth.org/Chloro.git
version: 0.06
